"""added folder name

Revision ID: 1bdbbe2d0aa7
Revises: d9a717e19218
Create Date: 2025-05-10 12:08:09.241553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdbbe2d0aa7'
down_revision = 'd9a717e19218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_name', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint('uq_user_folder_name', ['folder_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_folder_name', type_='unique')
        batch_op.drop_column('folder_name')

    # ### end Alembic commands ###
