"""added extra_storage_mb for subscription plan

Revision ID: c4877efdb8f8
Revises: 17b76d98d417
Create Date: 2025-06-19 11:44:52.959903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4877efdb8f8'
down_revision = '17b76d98d417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_storage_mb', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('extra_storage_mb')

    # ### end Alembic commands ###
