name: Build and Push Image to GHCR

on:
  push:
    branches: [main]

env:
  USERNAME: ${{ github.actor }}
  REPO: klka-drive

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set version from date
        run: echo "VERSION=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.USERNAME }}/${{ env.REPO }}:${{ env.VERSION }} \
            -t ghcr.io/${{ env.USERNAME }}/${{ env.REPO }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.USERNAME }}/${{ env.REPO }}:${{ env.VERSION }}
          docker push ghcr.io/${{ env.USERNAME }}/${{ env.REPO }}:latest

      # Optional: logout
      - name: Logout from GHCR
        run: docker logout ghcr.io
  
  deploys:
    runs-on: ubuntu-latest

    steps:
      - name: Set up gcloud CLI and authenticate
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: SSH and deploy to VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_NAME }} --zone=${{ secrets.GCP_VM_ZONE }} --command="
            cd cloud_pbl &&
            docker compose down &&
            docker rmi ghcr.io/kamalkoranga/klka-drive:latest &&
            docker compose up -d
          "

      - name: Logout from gcloud
        run: gcloud auth revoke --all
